# Generated by Django 4.2 on 2025-05-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('is_independent', models.BooleanField(default=True)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('openstreetmap_link', models.URLField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_latitude', models.FloatField(blank=True, null=True)),
                ('capital_longitude', models.FloatField(blank=True, null=True)),
                ('flag_png', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('flag_alt', models.TextField(blank=True, null=True)),
                ('coat_of_arms_org', models.URLField(blank=True, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('border', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('probability', models.FloatField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'ordering': ['-probability'],
                'unique_together': {('name', 'country')},
            },
        ),
    ]
